## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: jwtgen

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build
        run: ./mvnw verify -B
      - name: Build Container Image
        run: |
          IMAGE_NAME=${{ github.repository_owner }}/$APP_NAME
          IMAGE_ID=ghcr.io/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{ github.ref_name }}
          
          mvn package -DskipTests
          docker build -t $IMAGE_ID:$VERSION . -f src/main/docker/Dockerfile.jvm
      - name: Push Image
        run: |
          # Log in to registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker images
          
          IMAGE_NAME=${{ github.repository_owner }}/$APP_NAME
          IMAGE_ID=ghcr.io/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{ github.ref_name }}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker push $IMAGE_ID:$VERSION
          echo VERSION=$VERSION
          docker push $IMAGE_ID:$VERSION
